openapi: 3.0.0
info:
  version: '0.1'
  title: Kytos Circuit Provisioning
  description: Kytos NApp for provisioning of SDN circuits.
basePath: /kytos/circuit_provisioning
schemes:
  - https
tags:
  - name: Future
paths:

  /api/kytos/mef_eline/v2/evc/<circuit_id>:
    get:
      summary: "This endpoint will be implemented in the future"
      description: "This endpoint will be implemented in the future"
      tags:
        - Future
  /api/kytos/mef_eline/v2/evc/:
    get:
      summary: "This endpoint will be implemented in the future"
      description: "This endpoint will be implemented in the future"
      tags:
        - Future
    post:
      summary: Create a new Ethernet Virtual Circuit
      description: Creates a new circuit based on the given endpoints and constraints
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "Information needed to create the EVC"
                  example: "example circuit"
                uni_a:
                  type: object
                  properties:
                    interface_id:
                      description: "Identifier for the UNI A interface."
                      type: string
                    tag:
                      type: object
                      description: "Tag to be used in this endpoint. This is an optional parameter."
                      required: false
                      properties:
                        tag_type:
                          description: "Number of a tag type"
                          type: integer
                          example: 1
                        value:
                          description: "Value of a tag type"
                          type: integer
                          example: 80
                uni_b:
                  type: object
                  properties:
                    interface_id:
                      description: "Identifier for the UNI B interface."
                      type: string
                    tag:
                      type: object
                      required: false
                      description: "Tag to be used in this endpoint. This is an optional parameter."
                      properties:
                        tag_type:
                          description: "Number of a tag type"
                          type: integer
                          example: 4
                        value:
                          description: "Value of a tag type"
                          type: integer
                          example: 30

      responses:
        '201':
          description: "Circuit create successly"
          content:
            application/json:
              schema:
                type: object
                properties:
                  circuit_id:
                    type: string
                    description: "A circuit identifier"
                    example: "example circuit"
        '400':
          description: "Circuit creation error."
          content:
            application/json:
              schema:
                type: string
                description: "Details about the error encountered while creating the circuit."
                example: "Bad request: Invalid UNI."
